name: ci
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]
      - name: Lint
        run: |
          . .venv/bin/activate
          flake8 fmsim main.py scripts tests
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
      - name: Headless render
        run: |
          . .venv/bin/activate
          python scripts/sim_headless.py --out artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: headless-artifacts
          path: artifacts/
